# Generated by Django 3.2.5 on 2021-07-11 17:43

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BienesApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Bienes',
            fields=[
                ('base_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='BienesApp.base')),
                ('articulo', models.CharField(max_length=255)),
                ('descripcion', models.CharField(max_length=255)),
                ('usuario_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BienesApp.customuser')),
            ],
            bases=('BienesApp.base',),
        ),
    ]
